# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/ocrwkv.cpp/ocrwkv.cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/ocrwkv.cpp/ocrwkv.cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/ocrwkv.cpp/ocrwkv.cpp/CMakeFiles /home/runner/work/ocrwkv.cpp/ocrwkv.cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/ocrwkv.cpp/ocrwkv.cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencog_ml_example

# Build rule for target.
opencog_ml_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencog_ml_example
.PHONY : opencog_ml_example

# fast build rule for target.
opencog_ml_example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml_example.dir/build.make CMakeFiles/opencog_ml_example.dir/build
.PHONY : opencog_ml_example/fast

#=============================================================================
# Target rules for targets named test_opencog_ml

# Build rule for target.
test_opencog_ml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_opencog_ml
.PHONY : test_opencog_ml

# fast build rule for target.
test_opencog_ml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_opencog_ml.dir/build.make CMakeFiles/test_opencog_ml.dir/build
.PHONY : test_opencog_ml/fast

#=============================================================================
# Target rules for targets named rwkv

# Build rule for target.
rwkv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rwkv
.PHONY : rwkv

# fast build rule for target.
rwkv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rwkv.dir/build.make CMakeFiles/rwkv.dir/build
.PHONY : rwkv/fast

#=============================================================================
# Target rules for targets named opencog_ml

# Build rule for target.
opencog_ml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencog_ml
.PHONY : opencog_ml

# fast build rule for target.
opencog_ml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml.dir/build.make CMakeFiles/opencog_ml.dir/build
.PHONY : opencog_ml/fast

#=============================================================================
# Target rules for targets named test_ggml_basics

# Build rule for target.
test_ggml_basics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ggml_basics
.PHONY : test_ggml_basics

# fast build rule for target.
test_ggml_basics/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ggml_basics.dir/build.make tests/CMakeFiles/test_ggml_basics.dir/build
.PHONY : test_ggml_basics/fast

#=============================================================================
# Target rules for targets named test_quantized_matmul_on_gpu

# Build rule for target.
test_quantized_matmul_on_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_quantized_matmul_on_gpu
.PHONY : test_quantized_matmul_on_gpu

# fast build rule for target.
test_quantized_matmul_on_gpu/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_quantized_matmul_on_gpu.dir/build.make tests/CMakeFiles/test_quantized_matmul_on_gpu.dir/build
.PHONY : test_quantized_matmul_on_gpu/fast

#=============================================================================
# Target rules for targets named test_tiny_rwkv

# Build rule for target.
test_tiny_rwkv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tiny_rwkv
.PHONY : test_tiny_rwkv

# fast build rule for target.
test_tiny_rwkv/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_tiny_rwkv.dir/build.make tests/CMakeFiles/test_tiny_rwkv.dir/build
.PHONY : test_tiny_rwkv/fast

#=============================================================================
# Target rules for targets named test_quantization_format_compatibility

# Build rule for target.
test_quantization_format_compatibility: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_quantization_format_compatibility
.PHONY : test_quantization_format_compatibility

# fast build rule for target.
test_quantization_format_compatibility/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_quantization_format_compatibility.dir/build.make tests/CMakeFiles/test_quantization_format_compatibility.dir/build
.PHONY : test_quantization_format_compatibility/fast

#=============================================================================
# Target rules for targets named test_logit_calculation_skipping

# Build rule for target.
test_logit_calculation_skipping: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_logit_calculation_skipping
.PHONY : test_logit_calculation_skipping

# fast build rule for target.
test_logit_calculation_skipping/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_logit_calculation_skipping.dir/build.make tests/CMakeFiles/test_logit_calculation_skipping.dir/build
.PHONY : test_logit_calculation_skipping/fast

#=============================================================================
# Target rules for targets named test_eval_sequence_in_chunks

# Build rule for target.
test_eval_sequence_in_chunks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_eval_sequence_in_chunks
.PHONY : test_eval_sequence_in_chunks

# fast build rule for target.
test_eval_sequence_in_chunks/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_eval_sequence_in_chunks.dir/build.make tests/CMakeFiles/test_eval_sequence_in_chunks.dir/build
.PHONY : test_eval_sequence_in_chunks/fast

#=============================================================================
# Target rules for targets named test_context_cloning

# Build rule for target.
test_context_cloning: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_context_cloning
.PHONY : test_context_cloning

# fast build rule for target.
test_context_cloning/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_context_cloning.dir/build.make tests/CMakeFiles/test_context_cloning.dir/build
.PHONY : test_context_cloning/fast

#=============================================================================
# Target rules for targets named rwkv_cpu_info

# Build rule for target.
rwkv_cpu_info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rwkv_cpu_info
.PHONY : rwkv_cpu_info

# fast build rule for target.
rwkv_cpu_info/fast:
	$(MAKE) $(MAKESILENT) -f extras/CMakeFiles/rwkv_cpu_info.dir/build.make extras/CMakeFiles/rwkv_cpu_info.dir/build
.PHONY : rwkv_cpu_info/fast

#=============================================================================
# Target rules for targets named rwkv_quantize

# Build rule for target.
rwkv_quantize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rwkv_quantize
.PHONY : rwkv_quantize

# fast build rule for target.
rwkv_quantize/fast:
	$(MAKE) $(MAKESILENT) -f extras/CMakeFiles/rwkv_quantize.dir/build.make extras/CMakeFiles/rwkv_quantize.dir/build
.PHONY : rwkv_quantize/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml-base.dir/build.make ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml.dir/build.make ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f ggml/src/CMakeFiles/ggml-cpu.dir/build.make ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

examples/opencog_ml_example.o: examples/opencog_ml_example.c.o
.PHONY : examples/opencog_ml_example.o

# target to build an object file
examples/opencog_ml_example.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml_example.dir/build.make CMakeFiles/opencog_ml_example.dir/examples/opencog_ml_example.c.o
.PHONY : examples/opencog_ml_example.c.o

examples/opencog_ml_example.i: examples/opencog_ml_example.c.i
.PHONY : examples/opencog_ml_example.i

# target to preprocess a source file
examples/opencog_ml_example.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml_example.dir/build.make CMakeFiles/opencog_ml_example.dir/examples/opencog_ml_example.c.i
.PHONY : examples/opencog_ml_example.c.i

examples/opencog_ml_example.s: examples/opencog_ml_example.c.s
.PHONY : examples/opencog_ml_example.s

# target to generate assembly for a file
examples/opencog_ml_example.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml_example.dir/build.make CMakeFiles/opencog_ml_example.dir/examples/opencog_ml_example.c.s
.PHONY : examples/opencog_ml_example.c.s

opencog_ml.o: opencog_ml.cpp.o
.PHONY : opencog_ml.o

# target to build an object file
opencog_ml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml.dir/build.make CMakeFiles/opencog_ml.dir/opencog_ml.cpp.o
.PHONY : opencog_ml.cpp.o

opencog_ml.i: opencog_ml.cpp.i
.PHONY : opencog_ml.i

# target to preprocess a source file
opencog_ml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml.dir/build.make CMakeFiles/opencog_ml.dir/opencog_ml.cpp.i
.PHONY : opencog_ml.cpp.i

opencog_ml.s: opencog_ml.cpp.s
.PHONY : opencog_ml.s

# target to generate assembly for a file
opencog_ml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencog_ml.dir/build.make CMakeFiles/opencog_ml.dir/opencog_ml.cpp.s
.PHONY : opencog_ml.cpp.s

rwkv.o: rwkv.cpp.o
.PHONY : rwkv.o

# target to build an object file
rwkv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rwkv.dir/build.make CMakeFiles/rwkv.dir/rwkv.cpp.o
.PHONY : rwkv.cpp.o

rwkv.i: rwkv.cpp.i
.PHONY : rwkv.i

# target to preprocess a source file
rwkv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rwkv.dir/build.make CMakeFiles/rwkv.dir/rwkv.cpp.i
.PHONY : rwkv.cpp.i

rwkv.s: rwkv.cpp.s
.PHONY : rwkv.s

# target to generate assembly for a file
rwkv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rwkv.dir/build.make CMakeFiles/rwkv.dir/rwkv.cpp.s
.PHONY : rwkv.cpp.s

tests/test_opencog_ml.o: tests/test_opencog_ml.c.o
.PHONY : tests/test_opencog_ml.o

# target to build an object file
tests/test_opencog_ml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_opencog_ml.dir/build.make CMakeFiles/test_opencog_ml.dir/tests/test_opencog_ml.c.o
.PHONY : tests/test_opencog_ml.c.o

tests/test_opencog_ml.i: tests/test_opencog_ml.c.i
.PHONY : tests/test_opencog_ml.i

# target to preprocess a source file
tests/test_opencog_ml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_opencog_ml.dir/build.make CMakeFiles/test_opencog_ml.dir/tests/test_opencog_ml.c.i
.PHONY : tests/test_opencog_ml.c.i

tests/test_opencog_ml.s: tests/test_opencog_ml.c.s
.PHONY : tests/test_opencog_ml.s

# target to generate assembly for a file
tests/test_opencog_ml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_opencog_ml.dir/build.make CMakeFiles/test_opencog_ml.dir/tests/test_opencog_ml.c.s
.PHONY : tests/test_opencog_ml.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-cpu"
	@echo "... opencog_ml"
	@echo "... opencog_ml_example"
	@echo "... rwkv"
	@echo "... rwkv_cpu_info"
	@echo "... rwkv_quantize"
	@echo "... test_context_cloning"
	@echo "... test_eval_sequence_in_chunks"
	@echo "... test_ggml_basics"
	@echo "... test_logit_calculation_skipping"
	@echo "... test_opencog_ml"
	@echo "... test_quantization_format_compatibility"
	@echo "... test_quantized_matmul_on_gpu"
	@echo "... test_tiny_rwkv"
	@echo "... examples/opencog_ml_example.o"
	@echo "... examples/opencog_ml_example.i"
	@echo "... examples/opencog_ml_example.s"
	@echo "... opencog_ml.o"
	@echo "... opencog_ml.i"
	@echo "... opencog_ml.s"
	@echo "... rwkv.o"
	@echo "... rwkv.i"
	@echo "... rwkv.s"
	@echo "... tests/test_opencog_ml.o"
	@echo "... tests/test_opencog_ml.i"
	@echo "... tests/test_opencog_ml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

